### ISSUE TITLE
Prism Rainbow closes Rack when choosing from Module Browser

### ISSUE THREAD

**Issue by Petervos2018** [SteveRussell33/Prism#9] opened 2022-05-03 22:32 UTC
Selecting it in the browser : 

[11.836 info src/app/Browser.cpp:86 chooseModel] Creating module Prism Rainbow
[11.836 info src/app/Browser.cpp:90 chooseModel] Creating module widget Prism Rainbow

and Rack 2.0.6 (stand alone) closes (windows 10 21H2) Prism 2.3.3

But this is intermittent ... sometimes it just loads.

**Comment by Petervos2018** [comment] 2022-05-03 22:56
Installed version 2.3.4 and haven't had a crash yet, ....

**Comment by SteveRussell33** [comment] 2022-05-04 00:49
Good news, made a few fixes that should be good.
Will leave this issue open for the time being, and I can close one of the others.

**Comment by SteveRussell33** [comment] 2022-05-12 12:15
Closing as v2.3.4 now in library.

**Closed as completed by SteveRussell33** 2022-05-12 12:15 UTC

**Comment by Petervos2018** [comment] 2022-07-18 22:25
To keep you in the loop,

Was just trying it out again, closed rack while deleting the module(s)....(I had 3 added to the patch, to test)

[29.849 info src/app/Browser.cpp:89 chooseModel] Creating module Prism Rainbow
[29.850 info src/app/Browser.cpp:93 chooseModel] Creating module widget Prism Rainbow
[30.027 info src/patch.cpp:211 saveAutosave] Saving autosave C:/Users/ME/Documents/Rack2/autosave/patch.json
[30.067 info src/settings.cpp:470 save] Saving settings C:/Users/ME/Documents/Rack2/settings.json
[35.732 info src/app/Browser.cpp:89 chooseModel] Creating module Prism Rainbow
[35.732 info src/app/Browser.cpp:93 chooseModel] Creating module widget Prism Rainbow
[40.415 info src/app/Browser.cpp:89 chooseModel] Creating module Prism Rainbow
[40.418 info src/app/Browser.cpp:93 chooseModel] Creating module widget Prism Rainbow

**Comment by SteveRussell33** [comment] 2022-07-19 05:34
Can't reproduce on Windows.

**Comment by Petervos2018** [comment] 2022-07-19 09:27
Even I could not ;)

Thanks for tying.

Peter.
